# Generated by Django 6.0.6 on 2026-07-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('ward', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Road', 'Road Issue'), ('Water', 'Water Supply'), ('Electricity', 'Electricity'), ('Cleanliness', 'Cleanliness'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
